service: app-was-pruebatecnica
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage}
  region: ${opt:stage}
  environment:
    MYSQL_HOST: ${file(./config/${opt:stage, 'dev'}.json):MYSQL_HOST}
    MYSQL_PORT: ${file(./config/${opt:stage, 'dev'}.json):MYSQL_PORT}
    MYSQL_USER: ${file(./config/${opt:stage, 'dev'}.json):MYSQL_USER}
    MYSQL_PW: ${file(./config/${opt:stage, 'dev'}.json):MYSQL_PW}
    MYSQL_DB: ${file(./config/${opt:stage, 'dev'}.json):MYSQL_DB}

plugins:
  - serverless-offline
  - serverless-openapi

functions:
  getStartWars:
    handler: infraestructure\handlers\sartWars-handler.getStartWars
    events:
      - httpApi:
          path: api/v1/startwars
          method: get
  
  createStartWar:
    handler: infraestructure\handlers\sartWars-handler.createStartWar
    events:
      - httpApi:
          path: api/v1/startwar
          method: post
          request:
            schema:
              application: ${file(infraestructure\handlers\schemas\startwars-schema.json)}
